"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Notion = exports.Sheets = exports.Gmail = exports.Slack = exports.Telegram = void 0;
var telegram_1 = require("./telegram");
Object.defineProperty(exports, "Telegram", { enumerable: true, get: function () { return telegram_1.Telegram; } });
var slack_1 = require("./slack");
Object.defineProperty(exports, "Slack", { enumerable: true, get: function () { return slack_1.Slack; } });
var gmail_1 = require("./gmail");
Object.defineProperty(exports, "Gmail", { enumerable: true, get: function () { return gmail_1.Gmail; } });
var google_sheets_1 = require("./google-sheets");
Object.defineProperty(exports, "Sheets", { enumerable: true, get: function () { return google_sheets_1.Sheets; } });
var notion_1 = require("./notion");
Object.defineProperty(exports, "Notion", { enumerable: true, get: function () { return notion_1.Notion; } });
